#import ../text/entity.gql
#import ../../page/custom.gql
#import ../../page/builtin.gql

fragment LinkRoute on ComponentLinkRoute {
  text
  style {
    ...LinkText
  }
  custom {
    ...PageCustom
  }
  builtin {
    ...PageBuiltin
  }
}
