#import ../file/entity.gql

fragment Social on Social {
  url
  icon {
    ...FileWrapper
  }
}

fragment SocialWrapper on SocialEntityResponse {
  data {
    attributes {
      ...Social
    }
  }
}
