fragment Page on Page {
  name
  path
  blog {
    id
    tag
    text
  }
  static {
    id
    content
  }
  localizations {
    data {
      id
      attributes {
        locale
      }
    }
  }
}
